# GET all books

GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

##############

# to create a new record in outr json file

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
  "title": "Romancham"
}

###########

# to update a record, pass the id at the end

PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
  "title" : "IPL"
}

##########################

# to delete a record , i.e pass the id

DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json